[package]
name = "randfill"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.0", features = ["derive"] }
filetime = "0.2.27"
nix = { version = "0.31.2", features = ["fs", "user"] }
rayon = "1.11.0"
walkdir = "2.5.0"
windows-sys = { version = "0.61.2", features = ["Win32_Security_Cryptography", "Win32_Foundation"] }
