name: Build RandFill

on:
  push:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      continue-on-error: true
      with:
        submodules: 'recursive'
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build for Linux
      run: |
        clang -DVERSION_NAME="\"$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")\"" -DVERSION_CODE=$(git rev-list --count HEAD 2>/dev/null || echo 0) -o randfill-x64 randfill.c

    - name: Upload Linux x86_64 binary
      uses: actions/upload-artifact@v4
      with:
        name: randfill-linux-x86_64
        path: randfill-x64

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      continue-on-error: true
      with:
        submodules: 'recursive'
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build for macOS
      run: |
        clang -DVERSION_NAME="\"$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")\"" -DVERSION_CODE=$(git rev-list --count HEAD 2>/dev/null || echo 0) -o randfill-arm64 randfill.c -arch arm64
        clang -DVERSION_NAME="\"$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")\"" -DVERSION_CODE=$(git rev-list --count HEAD 2>/dev/null || echo 0) -o randfill-x64 randfill.c -arch x86_64

    - name: Upload macOS x86_64 binary
      uses: actions/upload-artifact@v4
      with:
        name: randfill-macos-x86_64
        path: randfill-x64

    - name: Upload macOS arm64 binary
      uses: actions/upload-artifact@v4
      with:
        name: randfill-macos-arm64
        path: randfill-arm64

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      continue-on-error: true
      with:
        submodules: 'recursive'
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up MSVC x86_64
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Build for Windows x86_64
      run: |
        rc randfill.rc
        $verName = (git describe --tags --abbrev=0 2>$null) ?? "0.0.0"
        $verCode = (git rev-list --count HEAD 2>$null) ?? "0"
        cl "/DVERSION_NAME=`"$verName`"" "/DVERSION_CODE=$verCode" randfill.c randfill.res /O2 /Fe:randfill-x64.exe
        [IO.File]::WriteAllBytes(".\codesign.pfx",[Convert]::FromBase64String("${{ secrets.PFX_BASE64 }}"))
        signtool sign /f .\codesign.pfx /p "${{ secrets.PFX_PASSWORD }}" /fd SHA256 /tr http://timestamp.digicert.com /td SHA256 randfill-x64.exe

    - name: Upload Windows x86_64 binary
      uses: actions/upload-artifact@v4
      with:
        name: randfill-windows-x86_64
        path: randfill-x64.exe
