name: Build RandFill

on:
  push:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      continue-on-error: true
      with:
        submodules: 'recursive'
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build for Linux
      run: |
        clang -o randfill-x64 randfill.c

    - name: Upload Linux x86_64 binary
      uses: actions/upload-artifact@v4
      with:
        name: randfill-linux-x86_64
        path: randfill-x64

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      continue-on-error: true
      with:
        submodules: 'recursive'
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build for macOS
      run: |
        clang -o randfill-arm64 randfill.c -arch arm64
        clang -o randfill-x64 randfill.c -arch x86_64

    - name: Upload macOS x86_64 binary
      uses: actions/upload-artifact@v4
      with:
        name: randfill-macos-x86_64
        path: randfill-x64

    - name: Upload macOS arm64 binary
      uses: actions/upload-artifact@v4
      with:
        name: randfill-macos-arm64
        path: randfill-arm64

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      continue-on-error: true
      with:
        submodules: 'recursive'
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up MSVC x86_64
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Build for Windows x86_64
      run: |
        cl randfill.c /O2 /Fe:randfill-x64.exe

    - name: Upload Windows x86_64 binary
      uses: actions/upload-artifact@v4
      with:
        name: randfill-windows-x86_64
        path: randfill-x64.exe
