name: CI

on:
  push:
  pull_request:

jobs:
  run:
    name: Build for (${{ matrix.name }})
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            os: windows-latest
            target: x86_64-pc-windows-msvc
            arch: x86_64
          - name: Linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            arch: x86_64
          - name: macOS
            os: macos-latest
            target: aarch64-apple-darwin
            arch: aarch64
          - name: macOS
            os: macos-latest-large
            target: x86_64-apple-darwin
            arch: x86_64

    steps:
      - uses: actions/checkout@v6

      - name: Setup Rust toolchain
        run: |
          rustup toolchain install

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
          cache-all-crates: "true"

      - name: Build
        if: matrix.os == 'windows-latest'
        run: |
          rc randfill.rc
          cargo rustc --release --target ${{ matrix.target }} --bin randfill -- -C link-arg=/INPUT:randfill.res

      - name: Build
        if: matrix.os != 'windows-latest'
        run: |
          cargo build --release --all-targets --all-features --workspace --target ${{ matrix.target }}

      - name: Upload release
        uses: actions/upload-artifact@v7
        with:
          name: RandFill-${{ matrix.arch }}-${{ matrix.name }}
          path: "./target/${{ matrix.target }}/release/*"
